/ddg4/Gun/Particle e-
/ddg4/Gun/Energy 100*GeV
/ddg4/Gun/direction (-60, 0, -1000)
/run/beamOn 1
/ddg4/Gun/direction (-42, 42, -1000)
/run/beamOn 1
/ddg4/Gun/direction (0, 60,  -1000)
/run/beamOn 1
/ddg4/Gun/direction (42, 42, -1000)
/run/beamOn 1
/ddg4/Gun/direction (60, 0,  -1000)
/run/beamOn 1
/ddg4/Gun/direction (42, -42, -1000)
/run/beamOn 1
/ddg4/Gun/direction (0, -60, -1000)
/run/beamOn 1
/ddg4/Gun/direction (-42, -42, -1000)
/run/beamOn 1
/ddg4/Gun/direction (-60, 0, 1000)
/run/beamOn 1
/ddg4/Gun/direction (-42, 42, 1000)
/run/beamOn 1
/ddg4/Gun/direction (0, 60,  1000)
/run/beamOn 1
/ddg4/Gun/direction (42, 42, 1000)
/run/beamOn 1
/ddg4/Gun/direction (60, 0,  1000)
/run/beamOn 1
/ddg4/Gun/direction (42, -42, 1000)
/run/beamOn 1
/ddg4/Gun/direction (0, -60, 1000)
/run/beamOn 1
/ddg4/Gun/direction (-42, -42, 1000)
/run/beamOn 1
