name: linux
on: [push, pull_request]

jobs:
  centos7:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        COMPILER: [gcc11]
        LCG: [104]

    steps:
    - uses: actions/checkout@v4
    - uses: cvmfs-contrib/github-action-cvmfs@v4
    - uses: aidasoft/run-lcg-view@v4
      with:
        view-path: "/cvmfs/clicdp.cern.ch/iLCSoft/lcg/${{ matrix.LCG }}/nightly/x86_64-centos7-${{ matrix.COMPILER }}-opt"
        setup-script: "init_ilcsoft.sh"
        run: |
          mkdir build
          cd build
          cmake -G Ninja -C ${ILCSOFT}/ILCSoft.cmake -DBUILD_TESTING=ON -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always -Werror " ..
          ninja -k0
          ctest --output-on-failure -C SIM
          ninja install
